---
- name: systemctl daemon-reload
  systemd: daemon_reload=yes

- name: Enable and start Syncthing instances
  systemd: name=syncthing@{{ item }} enabled=yes state=started
  with_items: "{{ syncthing_users }}"
