---
- name: Converge
  hosts: all

  vars:
    syncthing_users:
      - syncuser0

  pre_tasks:
    # The Fedora 30+ container images have only C.UTF-8 installed
    - name: Create users
      user:
        name: "{{ item }}"
        password: "*"
        update_password: on_create
        shell: /bin/bash
      with_items: "{{ syncthing_users }}"

  tasks:
    - name: "Include syncthing"
      include_role:
        name: "ansible-syncthing"
